name: "Terraform Format Check"

on:
  workflow_call:
    outputs:
      fmt_status:
        description: "Status of the terraform fmt check"
        value: ${{ jobs.terraform_fmt.outputs.status }}
      fmt_output:
        description: "Output of the terraform fmt check"
        value: ${{ jobs.terraform_fmt.outputs.output }}

jobs:
  terraform_fmt:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.fmt.outcome }}
      output: ${{ steps.fmt.outputs.output }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      
      - name: Terraform Format
        id: fmt
        run: |
          cd $GITHUB_WORKSPACE
          # Capturar tanto stdout como stderr
          OUTPUT=$(terraform fmt -check -recursive ./terraform 2>&1)
          EXIT_CODE=$?
          
          # Establecer el estado
          if [ $EXIT_CODE -ne 0 ]; then
            echo "output=❌ Failed: $OUTPUT" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "output=✅ Passed" >> $GITHUB_OUTPUT
          fi
